#!/usr/bin/env python

# Running:
#   ./play_random <directory>
#   # You can control playback with the following keys:
#   #   'q' : quit
#   #   'n' : go to the next random song
#   #   'p' : pause/play

import contextlib
import fcntl
import os
import random
import select
import signal
import string
import subprocess
import sys
import threading
import termios
import time

@contextlib.contextmanager
def terminal_settings():
  fd = sys.stdin.fileno()
  try:
    # Make stdin nonblocking
    fl = fcntl.fcntl(fd, fcntl.F_GETFL)
    fcntl.fcntl(fd, fcntl.F_SETFL, fl | os.O_NONBLOCK)

    # Turn off canonical mode (to make input available immediately; as per
    # termios(3)), and turn off character echoing.
    oldterm = termios.tcgetattr(fd)
    newattr = termios.tcgetattr(fd)
    newattr[3] = newattr[3] & ~termios.ICANON & ~termios.ECHO
    termios.tcsetattr(fd, termios.TCSANOW, newattr)

    yield
  finally:
    # Restore original settings
    termios.tcsetattr(fd, termios.TCSAFLUSH, oldterm)

def get_keypress_if_any():
  key = None
  try:
    key = sys.stdin.read(1)
    if key != chr(27):
      return key

    # When escape key is pressed, there are no additional characters to read,
    # and IOError can be raised, but that is caught below.
    rest = sys.stdin.read(1)

    # Special multi-character handling for 'Home' and 'End' keys
    if rest == 'O':
      return key + rest + sys.stdin.read(1)

    # If the next char isn't '[', we don't know what kind of special multi-
    # character string it is so just return
    if rest != '[':
      return key + rest

    # We need at least one more character
    rest += sys.stdin.read(1)

    # Special multi-character handling for direction keys
    if rest[-1] == 'A':
      return 'Up'
    elif rest[-1] == 'B':
      return 'Down'
    elif rest[-1] == 'C':
      return 'Right'
    elif rest[-1] == 'D':
      return 'Left'

    # Special multi-character handling for 'Insert', 'Delete', 'Page Up',
    # 'Page Down', 'F$N' (with $N >= 5)
    if rest[-1] in '0123456789':
      while rest[-1] in '0123456789':
        rest += sys.stdin.read(1)

    # Return what we've found.
    return key + rest

  except IOError:
    return key

def play_videos(playlist, c):
  choices = os.listdir('.')
  bitbucket = open(os.devnull, 'w')
  while True:
    next = random.choice(choices)
    nextname = next
    if len(nextname) > 60:
      nextname = nextname[0:60]+"..."
    print("Playing {}".format(nextname))
    cmd = ['ffplay', '-nodisp', '-loglevel', 'quiet', '-autoexit', next]
    c['proc'] = subprocess.Popen(cmd, stdout=bitbucket)
    c['proc'].wait()

playlist_dir = os.path.join(os.environ['HOME'], 'playlists')
if not os.path.isdir(playlist_dir):
  raise SystemExit("Could not find playlist_dir!")
if len(sys.argv) < 2:
  playlists = [x for x in os.listdir(playlist_dir)
                       if os.path.isdir(os.path.join(playlist_dir, x))
                          and not x.endswith('-unclipped')]
  raise SystemExit("Syntax: {} {}".format(sys.argv[0], playlists))
playlist = sys.argv[1]
os.chdir(os.path.join(playlist_dir, playlist))
c = {}
vid_thread = threading.Thread(target=play_videos, args=(playlist, c))
vid_thread.daemon = True
vid_thread.start()
with terminal_settings():
  fd = sys.stdin.fileno()
  playing = True
  while True:
    select.select([fd], [], [])
    key = get_keypress_if_any()
    if key.lower() == 'q':
      print("Quitting.")
      c['proc'].terminate()
      break
    elif key.lower() == 'n':
      print("Skipping to next video.")
      c['proc'].terminate()
    elif key.lower() == 'p':
      playing ^= True
      if playing:
        c['proc'].send_signal(signal.SIGCONT)
      else:
        c['proc'].send_signal(signal.SIGSTOP)
    elif all(c in string.printable for c in key) and \
         key not in ''.join(chr(x) for x in (9, 32, 13, 10)):
      print("Unhandled key: "+key)
    else:
      key_sequence = '0x'+''.join(hex(ord(x))[2:] for x in key)
      print("Unknown key escape sequence: '{}' ({})".format(key, key_sequence))
